const x = 2;

//do a try block//

try{
    x.toUpperCase();
} catch {
    console.log("recovery")

}